### ISSUE TITLE
How do you convert C++ to EXE?

### ISSUE THREAD

**Issue by AmazingMech2418** [MasterOfTheTiger/MinecraftConstructionCalculator#2]

**Comment by MasterOfTheTiger** [comment]
Dev C++ is a good compiler tool for Windows. I use Linux now, so I use G++. This is an old repo, I made it before I really knew anything about GitHub.

**Comment by AmazingMech2418** [comment]
@MasterOfTheTiger I don't have that. Could you possibly convert https://github.com/amazinigmech2418/Learning-C- ?
